### ISSUE TITLE
Summary Script

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/MA_visualization#12]
I tried making a [summary script](https://github.com/VACILT/MA_visualization/blob/main/code/Script.ipynb). By only using layouts of hvplot or rather holoviews, it is only possible to make symmetrical  layouts. The four plots may only be arranged either one or two per row. GridSpec would help this problem, but then the transition from hvplot to html wouldn't work.

**Comment by kuchaale** [comment]
Looks great. Thx
