### ISSUE TITLE
Reproduce wind figure

### ISSUE THREAD

**Issue by kuchaale** [VACILT/MA_visualization#2]
Reproduce [this wind figure](https://meteo.physgeo.uni-leipzig.de/de/wetterdaten/radar_wind.php) in python.

- [x] read variable `/wind/u` and `/wind/v` from one of [these datasets](https://github.com/VACILT/MA_visualization/tree/main/data)
- [x] prepare static version of the figure
- [x] prepare interactive version of the figure
- [x] take into account zonal (`/wind/u_err`) and meridional (`/wind/v_err`) error

**Comment by stoeckel4code** [comment]
I added the error contours ([here](https://github.com/VACILT/MA_visualization/blob/73ef96bf47ee955d6ebe212f354007807c1b77f4/code/radar_wind.py#L64)). Question: What means the error? Is it means as v +/- error?

**Comment by kuchaale** [comment]
Exactly. Contours worked to mark statistically significant regions using p-values though. Can you use [shading](https://hvplot.holoviz.org/user_guide/Plotting.html#Area) or [error bars](https://hvplot.holoviz.org/reference/pandas/errorbars.html)?

**Comment by kuchaale** [comment]
In the case of shading, I also like [this one](https://hvplot.holoviz.org/reference/pandas/errorbars.html).

**Comment by stoeckel4code** [comment]
The errorbars looking fine for [this](https://github.com/VACILT/MA_visualization/blob/main/code/radar_wind.py#L60-L65) scatterplot
