### ISSUE TITLE
Reproduce summary figure

### ISSUE THREAD

**Issue by kuchaale** [VACILT/MA_visualization#4]
Reproduce [this summary figure](https://meteo.physgeo.uni-leipzig.de/de/wetterdaten/radar_analyse.php) in python. Related to #1.

**Comment by stoeckel4code** [comment]
Due to the website changes, the link isn't working. Do you have a new one?

**Comment by kuchaale** [comment]
![obrazek](https://user-images.githubusercontent.com/6815953/115709760-e3001f00-a371-11eb-8f1c-74ad4eb2433c.png)

**Comment by kuchaale** [comment]
I updated files so that they include geographical (see `/info/geo_lat` and `/info/geo_lon` variables) and altitudinal (see `/info/alt_dist/`) distribution of meteors.

**Comment by kuchaale** [comment]
> Due to the website changes, the link isn't working. Do you have a new one?

You can still access it [here](https://139.18.173.82/~meteo/radar.php) within the university network.

**Comment by kuchaale** [comment]
Done in #12.
