### ISSUE TITLE
understanding the h5 datasets

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/MA_visualization#5]
@kuchaale 
Some questions come up:

- What does the group "tides" represent and what are variables (A24u, p12u, etc ...)
- How do I handle the "phony_dim_#"?

**Comment by kuchaale** [comment]
- the tides group represents amplitude (A) and phase (p) of diurnal (24), semidiurnal (12) and terdiurnal (8) tidal either zonal (u) or meridional (v) wind component
- so far you need to rename it (see [read_webtool_radardata.ipynb](https://github.com/VACILT/MA_visualization/blob/main/code/read_webtool_radardata.ipynb)) to `time` and `altitude` dimensions. I may deal with it in a separate issue.
