### ISSUE TITLE
Prepare jupyter book to show visualizations

### ISSUE THREAD

**Issue by kuchaale** [VACILT/MA_visualization#8]
Prepare jupyter book full of all kinds of visualizations. See [VACILT/SSW_project#9](https://github.com/VACILT/SSW_project/issues/9) or [VACILT/trend_paper/#4](https://github.com/VACILT/trend_paper/issues/4)  for more information.

**Comment by kuchaale** [comment]
The Github page is ready on this address: [https://vacilt.github.io/MA_visualization/](https://vacilt.github.io/MA_visualization/). So far it is set to be built from the `/docs` folder in the `master` branch. We can manually put the content there as stated [here](https://jupyterbook.org/publish/gh-pages.html#manually-put-your-books-contents-online).

**Comment by kuchaale** [comment]
Shall I close this issue? Or is there anything TBD?

**Comment by stoeckel4code** [comment]
The think the preperation is done. Choosing the content is an other issue.
