### ISSUE TITLE
Deploy functional sliders/widgets on jupyter-book-page.

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/MA_visualization#9]
We are looking for the option, to implement full functional sliders to the static jupyter-notebook-page.  Some advices for interactivity are given [here](https://jupyterbook.org/interactive/interactive.html#bokeh), or [here](https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html#userguide-jupyter).

**Comment by kuchaale** [comment]
Does [Bokeh](https://jupyterbook.org/interactive/interactive.html#bokeh) with widgets (e.g. sliders) work when using `output_notebook()`?

**Comment by stoeckel4code** [comment]
No. I tried it on [this](https://vacilt.github.io/MA_visualization/radar_wind_bars.html) plot (associated [code](https://github.com/VACILT/MA_visualization/blob/main/book/radar_wind_bars.ipynb)). The altidude is selected by a widget. It runs locally but not in the jupyter book.
![image](https://user-images.githubusercontent.com/58188931/120463611-60b94080-c39c-11eb-9340-f045de0e3766.png)
![image](https://user-images.githubusercontent.com/58188931/120463700-79295b00-c39c-11eb-89c7-972450af8c52.png)

**Comment by stoeckel4code** [comment]
The problem is, that no python kernel is running. But there is a way to use the java script kernel, which runs in the browser. 
Using this ['callbacks'](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html) may be the solution. But we have to change our code completly.

**Comment by kuchaale** [comment]
Can you check [this issue](https://github.com/executablebooks/jupyter-book/issues/453)? The solution may be to export the bokeh notebook separately and then include it as an HTML file in the jupyter book.

**Comment by stoeckel4code** [comment]
I tried it like this:
```python
from bokeh.embed import file_html
from bokeh.resources import CDN
import IPython

html_repr = file_html(pn.Column(bars).get_root(), CDN)
IPython.display.HTML(html_repr)
```
this creates a html file but the widget don't works for now.

**Comment by kuchaale** [comment]
Do widgets in the exported HTML file work at least? Our issue related to issues that are still open, e.g. [executablebooks/jupyter-book#1077](https://github.com/executablebooks/jupyter-book/issues/1077) and  [executablebooks/jupyter-book#1113](https://github.com/executablebooks/jupyter-book/issues/1113). One suggestion is to include `html_extra_path` in `_config.yml` in the following way:
```markdown
sphinx:
  config:
    html_extra_path: path_to_external_html
```

**Comment by stoeckel4code** [comment]
I tried running my hv bars plot by:
```python
...
bars = ds_wind.hvplot.scatter(y=['u','v'], symmetric =True, ylim=[-100,100], groupby='alt')
import holoviews as hv
fig = hv.render(bars, backend='bokeh')
```
Than I have a figure which I can implement in this (analog to the [example](https://stackoverflow.com/questions/44281863/saving-html-file-with-images-in-bokeh/44282125)):
```python
from bokeh.plotting import figure, output_file, save

output_file("test.html")
save(fig)
```
This gives me a html-site, but the widget doesn't works.
My thoughts were, that I need a figure created by bokeh.plotting rather than holoviews or hvplot.
But bokeh.plotting doesn't works well with with the xarray dataset. Shall I try converting the dataset to a pandas dataset?
Or am I on a wrong way?

**Comment by kuchaale** [comment]
Indeed, it may be an issue. Can you try [this approach](https://hvplot.holoviz.org/user_guide/Viewing.html#saving-plots)?

**Comment by stoeckel4code** [comment]
Thank you, this works fine!
